//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Comic
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Comic()
        {
            this.MainCharacter = "Our Hero";
            this.IssueNumber = 0;
            this.SeriesTitle = "Title";
            this.SeriesNumber = 0;
            this.Commemoration = "none";
            this.OriginalValue = 0.00m;
            this.Condition = "Raw";
            this.Comments = "No comment";
            this.Authors = new HashSet<Author>();
            this.Valuations = new HashSet<Valuation>();
        }
    
        public int ComicsId { get; set; }
        public int PublisherId { get; set; }
        public string MainCharacter { get; set; }
        public System.DateTime PublishDate { get; set; }
        public string Illustrator { get; set; }
        public int IssueNumber { get; set; }
        public string PhotoFileName { get; set; }
        public string SeriesTitle { get; set; }
        public int SeriesNumber { get; set; }
        public string SecondaryCharacter { get; set; }
        public string Commemoration { get; set; }
        public decimal OriginalValue { get; set; }
        public string Condition { get; set; }
        public int StorageBoxId { get; set; }
        public string Comments { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Author> Authors { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Valuation> Valuations { get; set; }
    }
}
