//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ComicsDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Valuation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Valuation()
        {
            this.Value = 0.00m;
            this.Condition = "Raw";
            this.Source = "n/a";
        }
    
        public int ValuationId { get; set; }
        public decimal Value { get; set; }
        public string Condition { get; set; }
        public string Source { get; set; }
        public System.DateTime Date { get; set; }
        public int ComicComicsId { get; set; }
    
        public virtual Comic Comic { get; set; }
    }
}
